In [4]:
import numpy as np
import pandas as pd

In [5]:
def validate_data(
        file_path: str = "../data/raw/bama_backup.csv",
) -> pd.DataFrame:
    # load data
    df = pd.read_csv(file_path)
    print("Data loaded successfully.")
    print(f"Dataset Shape: {df.shape}")
    print("--" * 30)

	# check for duplicate columns
    print("Checking for duplicate columns...\n")
    if df.duplicated(subset="link", keep="first").sum() == 0:
        print("No duplicate columns found.")
    else:
        print("Duplicate column names found.")
    print("--" * 30)

	# check for data type consistency
    print("Checking for data type consistency...\n")
    df_dtypes = pd.DataFrame(df.dtypes, columns=["raw_dtype"])
    df_dtypes['expected_dtype_to_be'] = [
		"str",
		"str",
		"str",
		"int64",
		"int64",
		"str",
		"category",
		"category",
		"category",
		"category",
		"category",
		"category",
		"category",
		"int64",
		"datetime64[ns]",
		"category",
		"int64",
		"str",
		"datetime64[ns]"
	]
    if (df_dtypes['raw_dtype'] != df_dtypes['expected_dtype_to_be']).any():
        print("Data type inconsistency found.")
        columns_needs_correction = df_dtypes.loc[
            df_dtypes['raw_dtype'] != df_dtypes['expected_dtype_to_be']
		].index.to_list()
        print(f"Columns that need correction: {columns_needs_correction}")
    else:
        print("Data type consistency found.")
    print("--" * 30)

	# check for missing values
    print("Checking for missing values...\n")
    if df.isna().sum().sum() == 0:
        print("No missing values found.")
    else:
        print("Missing values found.")

    columns_with_missing_values = []
    for column in df.columns:
        if df.isna().sum().loc[column] != 0:
            columns_with_missing_values.append(column)
    print(f"Columns with missing values: {columns_with_missing_values}")
    print("--" * 30)

    return df, df_dtypes

df, df_dtypes = validate_data()

Data loaded successfully.
Dataset Shape: (39661, 19)
------------------------------------------------------------
Checking for duplicate columns...

No duplicate columns found.
------------------------------------------------------------
Checking for data type consistency...

Data type inconsistency found.
Columns that need correction: ['transmission', 'fuel', 'body_color', 'inside_color', 'body_status', 'body_type', 'cylinder_fa', 'modified_date', 'brand', 'scraped_at']
------------------------------------------------------------
Checking for missing values...

Missing values found.
Columns with missing values: ['fuel', 'cylinder_fa']
------------------------------------------------------------

In [6]:
def load_data(file_path: str = "../data/raw/bama_backup.csv") -> pd.DataFrame:
    # Read the raw data from the specified file path.
    df = pd.read_csv(file_path, encoding="utf-8")
    return df

load_data()

,title,subtitle,trim,year,mileage,location,transmission,fuel,body_color,inside_color,body_status,body_type,cylinder_fa,image_count,modified_date,brand,price,link,scraped_at
0,سیتروئن، C3 XR,1404 | تیپ V1,تیپ V1,1404,0,تهران / ستارخان,اتوماتیک,بنزینی,مشکی,مشکی,بدون رنگ,crossover,3 سیلندر,3,2026-09-19T13:10:34.81,citroen,3850000000,https://bama.ir/car/detail-jj5hqcwr-citroen-c3...,2026-10-14
1,لوکانو، L7,1405 | 1.6 لیتر توربو,1.6 لیتر توربو,1405,0,تهران / میرداماد,اتوماتیک,بنزینی,سفید,مشکی,بدون رنگ,crossover,4 سیلندر,4,2026-10-12T09:48:06.4,lucano,0,https://bama.ir/car/detail-4xe7cfvb-lucano-l7-...,2026-10-14
2,هیوندای، النترا,2025 | 1.5 لیتر,1.5 لیتر,2025,0,تهران / ستارخان,اتوماتیک,بنزینی,سفید,مشکی,بدون رنگ,passenger_car,4 سیلندر,3,2026-09-19T13:12:43.71,hyundai,6700000000,https://bama.ir/car/detail-s4abyrv3-hyundai-el...,2026-10-14
3,چانگان، CS 55 پلاس,2024 | 1.5 لیتر توربو,1.5 لیتر توربو,2024,28000,تهران / ولنجک,اتوماتیک,بنزینی,خاکستری,مشکی,بدون رنگ,crossover,4 سیلندر,6,2026-10-12T19:16:06.27,changan,6550000000,https://bama.ir/car/detail-vybyrlkv-changan-cs...,2026-10-14
4,کی ام سی، T8,1403,دنده ای,1403,30000,تهران / میرداماد,دنده ای,بنزینی,مشکی,مشکی,بدون رنگ,pickup,4 سیلندر,2,2026-10-13T21:13:28.18,kmc,0,https://bama.ir/car/detail-fpvuq3wv-kmc-t8-1403,2026-10-14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39656,ب ام و، سری 5 سدان,2015 | 528i,528i,2015,77000,اصفهان / سعادت آباد,اتوماتیک,بنزینی,سفید,مارون,بدون رنگ,passenger_car,4 سیلندر,8,2025-09-07T11:40:13.65,bmw,0,https://bama.ir/car/detail-nyzsdxyl-bmw-5serie...,2026-10-14
39657,ب ام و، سری 5 سدان,2018 | 530i,530i,2018,49000,اصفهان / خیابان نظر غربی,اتوماتیک,بنزینی,مشکی,موکا,بدون رنگ,passenger_car,4 سیلندر,11,2025-01-15T20:24:22.58,bmw,0,https://bama.ir/car/detail-mcdae3b9-bmw-5serie...,2026-10-14
39658,نیسان، ترا,1404 | اکسکلوسیو,اکسکلوسیو,1404,0,اصفهان / سعادت آباد,اتوماتیک,بنزینی,مشکی,مارون,بدون رنگ,suv,4 سیلندر,7,2025-08-30T11:23:21.82,nissan,0,https://bama.ir/car/detail-wtgptycz-nissan-ter...,2026-10-14
39659,ب ام و، سری 7,2017 | 730li,730li,2017,42000,اصفهان / خیابان نظر غربی,اتوماتیک,بنزینی,سفید صدفی,مارون,بدون رنگ,passenger_car,4 سیلندر,0,2024-01-23T13:42:27.1,bmw,0,https://bama.ir/car/detail-lm8xhqo2-bmw-7serie...,2026-10-14
39660,پراید، صندوق دار,1387,دنده ای,1387,300000,شاهین دژ / پمپ بنزین,دنده ای,بنزینی,نقره ای,طوسی,بدون رنگ,passenger_car,4 سیلندر,1,2020-04-06T09:43:11.21,pride,0,https://bama.ir/car/detail-4y13ydvg-pride-seda...,2026-10-14

In [7]:
df.isnull().sum()

title               0
subtitle            0
trim                0
year                0
mileage             0
location            0
transmission        0
fuel                4
body_color          0
inside_color        0
body_status         0
body_type           0
cylinder_fa      1618
image_count         0
modified_date       0
brand               0
price               0
link                0
scraped_at          0
dtype: int64

- Dataset contains 39,661 rows and 19 columns than one of them is the link column which is not needed for the analysis.

- No duplicates in the dataset.

- Data types of these columns need to be fixed:
  - transmission: **str** -> **categorical**
  - fuel: **str** -> **categorical**
  - body_color: **str** -> **categorical**
  - inside_color: **str** -> **categorical**
  - body_status: **str** -> **categorical**
  - body_type: **str** -> **categorical**
  - cylinder_fa: **str** -> **categorical**
  - modified_date: **str** -> **datetime**
  - brand: **str** -> **categorical**
  - scraped_at: **str** -> **datetime**

- Missing values found in the dataset:
  - **cylinder_fa:** 1618
  - **fuel:** 4

In [8]:
df_dtypes

              raw_dtype expected_dtype_to_be
title               str                  str
subtitle            str                  str
trim                str                  str
year              int64                int64
mileage           int64                int64
location            str                  str
transmission        str             category
fuel                str             category
body_color          str             category
inside_color        str             category
body_status         str             category
body_type           str             category
cylinder_fa         str             category
image_count       int64                int64
modified_date       str       datetime64[ns]
brand               str             category
price             int64                int64
link                str                  str
scraped_at          str       datetime64[ns]

In [9]:
df.loc[df['subtitle'].str.split('|', expand=True)[1].isnull(), 'trim'].value_counts()

trim
دنده ای     3480
اتوماتیک    2763
Name: count, dtype: int64

In [10]:
df['title'].str.split('،', expand=True)[0].value_counts()

0
پژو                6122
تویوتا             3144
دنا                1768
کوییک              1761
ام وی ام           1692
                   ...
سیناد                 1
حواله لندرور          1
حواله میتسوبیشی       1
پیش فروش اپل          1
پیش فروش بنز          1
Name: count, Length: 202, dtype: int64

In [11]:
df['trim'].value_counts()

trim
دنده ای                      4487
اتوماتیک                     3696
1.5 لیتر توربو               1690
تیپ 2                        1533
2.0 لیتر                      961
                             ...
1.5 لیتر مکس اسپرت لاکچری       1
640i                            1
2.0 لیتر تيپ 2                  1
2.3 لیتر پرستیژ                 1
فایتر (توربو)                   1
Name: count, Length: 598, dtype: int64

In [12]:
df['transmission'].value_counts()

transmission
اتوماتیک    24036
دنده ای     15625
Name: count, dtype: int64

In [13]:
df['fuel'].value_counts()

fuel
بنزینی           33807
هیبریدی           2011
برقی              1551
دوگانه سوز         844
پلاگین هیبرید      677
هیبرید ملایم       371
بردافزا            348
دیزلی               48
Name: count, dtype: int64

**Mappings**

Persian | English | Abbreviation

- بنزینی - Gasoline / Petrol - ICE
- هیبریدی - Full Hybrid - HEV
- برقی - Battery Electric- BEV / EV
- دوگانه سوز - Bi-Fuel (Gasoline + CNG) - Bi-Fuel
- پلاگین هیبرید - Plug-in Hybrid - PHEV
- هیبرید ملایم - Mild Hybrid	- MHEV
- بردافزا - Range-Extended Electric Vehicle - EREV / REEV
- دیزلی - Diesel - Diesel

In [14]:
df.loc[df['fuel'].isnull()]

,title,subtitle,trim,year,mileage,location,transmission,fuel,body_color,inside_color,body_status,body_type,cylinder_fa,image_count,modified_date,brand,price,link,scraped_at
35618,مازراتی، لوانته,2022 | S,S,2022,20000,تهران / سعادت‌آباد,اتوماتیک,NaN,آبی,موکا,بدون رنگ,crossover,NaN,5,2026-05-08T15:57:49.25,maserati,0,https://bama.ir/car/detail-0au3h4cz-maserati-l...,2026-10-14
38383,تویوتا، هایلوکس دو کابین,2016 | بلند دنده ای,بلند دنده ای,2016,65000,شیراز / معالی‌آباد,دنده ای,NaN,مشکی,قرمز,بدون رنگ,pickup,4 سیلندر,4,2026-09-01T15:55:09.55,toyota,0,https://bama.ir/car/detail-mbkrog6x-toyota-hil...,2026-10-14
38403,تویوتا، هایلوکس دو کابین,2010 | بلند دنده ای,بلند دنده ای,2010,258000,تهران / اقدسیه,دنده ای,NaN,سفید,-,یک لکه رنگ,pickup,4 سیلندر,3,2026-09-09T12:58:24.3,toyota,5800000000,https://bama.ir/car/detail-kkewb5ox-toyota-hil...,2026-10-14
38998,ب ام و، سری 6 گرن کوپه,2013 | 640i,640i,2013,65000,تهران / اقدسیه,اتوماتیک,NaN,سفید,-,یک لکه رنگ,passenger_car,6 سیلندر,3,2026-09-09T12:57:30.87,bmw,19890000000,https://bama.ir/car/detail-ce1uizys-bmw-6serie...,2026-10-14

In [15]:
df['body_color'].value_counts().index

Index(['سفید', 'مشکی', 'خاکستری', 'نقره ای', 'نوک مدادی', 'سفید صدفی', 'آبی',
       'تیتانیوم', 'سرمه ای', 'قهوه ای', 'بژ', 'قرمز', 'طوسی', 'یشمی',
       'کربن بلک', 'ذغالی', 'بادمجانی', 'سبز', 'آلبالویی', 'دلفینی', 'نقرآبی',
       '-', 'کرم', 'زرد', 'زیتونی', 'اطلسی', 'سربی', 'بنفش', 'مسی', 'طلائی',
       'نارنجی', 'زرشکی', 'موکا', 'عنابی', 'برنز', 'عدسی', 'خاکی', 'یاسی',
       'گیلاسی', 'شتری', 'مارون', 'اخرائی', 'صورتی', 'پوست پیازی', 'امبر بلک',
       'تارتوفو'],
      dtype='str', name='body_color')

In [16]:
df['inside_color'].value_counts().index

Index(['مشکی', '-', 'کرم', 'خاکستری', 'قرمز', 'موکا', 'مارون', 'سفید',
       'قهوه ای', 'طوسی', 'نقره ای', 'نوک مدادی', 'بژ', 'نارنجی', 'شتری',
       'آبی', 'سرمه ای', 'امبر بلک', 'تارتوفو', 'دلفینی', 'تیتانیوم',
       'بادمجانی', 'آلبالویی', 'زرشکی', 'سفید صدفی', 'بنفش', 'مسی', 'عنابی',
       'طلائی', 'زرد', 'خاکی', 'اطلسی', 'سربی', 'کربن بلک', 'اخرائی', 'یشمی',
       'سبز', 'ذغالی', 'زیتونی', 'عدسی', 'نقرآبی', 'برنز', 'گیلاسی',
       'پوست پیازی', 'صورتی', 'یاسی'],
      dtype='str', name='inside_color')

In [17]:
df['body_status'].value_counts()

body_status
بدون رنگ            28191
چند لکه رنگ          2053
یک لکه رنگ           1799
دور رنگ              1708
دو لکه رنگ           1620
خط و خش جزئی         1119
صافکاری بدون رنگ      680
کامل رنگ              611
گلگیر رنگ             464
گلگیر تعویض           277
کاپوت تعویض           266
کاپوت رنگ             219
یک درب رنگ            173
دو درب رنگ            146
درب تعویض             143
تصادفی                110
اتاق تعویض             56
سوخته                  21
اوراقی                  5
Name: count, dtype: int64

In [18]:
df['body_type'].value_counts()

body_type
passenger_car    16300
crossover        11931
hatchback         7906
suv               1656
pickup            1511
van                187
coupe              103
convertible         67
Name: count, dtype: int64

In [19]:
df['cylinder_fa'].value_counts()

cylinder_fa
4 سیلندر    35354
6 سیلندر     1812
3 سیلندر      645
8 سیلندر      225
5 سیلندر        7
Name: count, dtype: int64

In [20]:
def get_cylinder_fa_missings_not_electric(df):
	df = df.loc[df['cylinder_fa'].isnull()]
	return df.loc[df['fuel'] != "برقی"]

get_cylinder_fa_missings_not_electric(df)

,title,subtitle,trim,year,mileage,location,transmission,fuel,body_color,inside_color,body_status,body_type,cylinder_fa,image_count,modified_date,brand,price,link,scraped_at
540,کی ام سی، J7,1405,اتوماتیک,1405,0,تهران / تهران‌ویلا,اتوماتیک,بنزینی,سفید,مشکی,بدون رنگ,passenger_car,NaN,2,2026-10-04T11:04:33.41,kmc,6200000000,https://bama.ir/car/detail-cyrbms0u-kmc-j7-1405,2026-10-14
570,شاهین، G دنده ای,1404,دنده ای,1404,0,تهران / قیطریه,دنده ای,بنزینی,سفید,مشکی,بدون رنگ,passenger_car,NaN,1,2026-06-28T15:21:55.65,shahin,3450000000,https://bama.ir/car/detail-e65rkxi1-shahin-g-1404,2026-10-14
596,دیگنیتی، پرایم,1404,اتوماتیک,1404,0,تهران / ستارخان,اتوماتیک,بنزینی,سفید,مشکی,بدون رنگ,crossover,NaN,2,2026-06-16T15:30:21.77,dignity,0,https://bama.ir/car/detail-akx0h1w4-dignity-pr...,2026-10-14
605,دیگنیتی، پرایم,1404,اتوماتیک,1404,0,تهران / ستارخان,اتوماتیک,بنزینی,سفید,مارون,بدون رنگ,crossover,NaN,2,2026-06-16T15:29:34.99,dignity,0,https://bama.ir/car/detail-ivy34bkx-dignity-pr...,2026-10-14
616,دیگنیتی، پرایم,1404,اتوماتیک,1404,0,تهران / ستارخان,اتوماتیک,بنزینی,سفید,مشکی,بدون رنگ,crossover,NaN,1,2026-05-24T16:58:41.68,dignity,0,https://bama.ir/car/detail-ggldljdy-dignity-pr...,2026-10-14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39432,پورشه، ماکان,2017,اتوماتیک,2017,84000,اصفهان / هشت بهشت غربی,اتوماتیک,بنزینی,سفید,قرمز,بدون رنگ,crossover,NaN,12,2026-05-28T12:54:43.77,porsche,0,https://bama.ir/car/detail-pazvh6rg-porsche-ma...,2026-10-14
39564,پورشه، ماکان,2017,اتوماتیک,2017,75000,اصفهان / خیابان نظر غربی,اتوماتیک,بنزینی,مشکی,مشکی,بدون رنگ,crossover,NaN,9,2026-07-01T17:13:56.74,porsche,0,https://bama.ir/car/detail-hurgdzeg-porsche-ma...,2026-10-14
39586,پورشه، ماکان,2017,اتوماتیک,2017,85000,تهران / شهید بهشتی,اتوماتیک,بنزینی,سفید,مارون,بدون رنگ,crossover,NaN,8,2025-09-24T13:30:04.9,porsche,0,https://bama.ir/car/detail-ypbe0zjn-porsche-ma...,2026-10-14
39591,ب ام و، X4,2015 | 28,28,2015,70000,تهران / شهید بهشتی,اتوماتیک,بنزینی,مشکی,موکا,بدون رنگ,crossover,NaN,4,2025-09-24T13:30:04.49,bmw,0,https://bama.ir/car/detail-xtgz0o2e-bmw-x4-28-...,2026-10-14
39600,پورشه، ماکان,2017,اتوماتیک,2017,75000,اصفهان / ابوالحسنی,اتوماتیک,بنزینی,مشکی,مشکی,بدون رنگ,crossover,NaN,6,2026-01-19T13:26:45.49,porsche,0,https://bama.ir/car/detail-rscmyihz-porsche-ma...,2026-10-14

In [21]:
df['modified_date']

# df['modified_date'].str.slice(0,10)

0        2026-09-19T13:10:34.81
1         2026-10-12T09:48:06.4
2        2026-09-19T13:12:43.71
3        2026-10-12T19:16:06.27
4        2026-10-13T21:13:28.18
                  ...
39656    2025-09-07T11:40:13.65
39657    2025-01-15T20:24:22.58
39658    2025-08-30T11:23:21.82
39659     2024-01-23T13:42:27.1
39660    2020-04-06T09:43:11.21
Name: modified_date, Length: 39661, dtype: str

In [22]:
df.loc[:, 'brand'].value_counts()

brand
peugeot      6265
toyota       3240
dena         1883
quick        1873
mvm          1705
             ...
hyosow          1
leapmotor       1
luxgen          1
infiniti        1
sinad           1
Name: count, Length: 135, dtype: int64

In [23]:
df_dtypes

              raw_dtype expected_dtype_to_be
title               str                  str
subtitle            str                  str
trim                str                  str
year              int64                int64
mileage           int64                int64
location            str                  str
transmission        str             category
fuel                str             category
body_color          str             category
inside_color        str             category
body_status         str             category
body_type           str             category
cylinder_fa         str             category
image_count       int64                int64
modified_date       str       datetime64[ns]
brand               str             category
price             int64                int64
link                str                  str
scraped_at          str       datetime64[ns]

In [24]:
def load_data(file_path: str = "../data/raw/bama_backup.csv") -> pd.DataFrame:
    # Read the raw data from the specified file path.
    df = pd.read_csv(file_path, encoding="utf-8")

	# handle missing values
    # fuel column
    df.loc[35618, 'fuel'] = 'بنزینی'
    df.loc[38383, 'fuel'] = 'بنزینی'
    df.loc[38403, 'fuel'] = 'بنزینی'
    df.loc[38998, 'fuel'] = 'بنزینی'

	# cylinder_fa column
    df_missing = df.loc[df['cylinder_fa'].isnull()]
    df_missing.loc[
		df_missing['fuel'] == 'برقی', 'cylinder_fa'
	] = "0"

	# df_missing.loc[df_missing['fuel'] == 'بنزینی', 'title']
    return df

df = load_data()
df

,title,subtitle,trim,year,mileage,location,transmission,fuel,body_color,inside_color,body_status,body_type,cylinder_fa,image_count,modified_date,brand,price,link,scraped_at
0,سیتروئن، C3 XR,1404 | تیپ V1,تیپ V1,1404,0,تهران / ستارخان,اتوماتیک,بنزینی,مشکی,مشکی,بدون رنگ,crossover,3 سیلندر,3,2026-09-19T13:10:34.81,citroen,3850000000,https://bama.ir/car/detail-jj5hqcwr-citroen-c3...,2026-10-14
1,لوکانو، L7,1405 | 1.6 لیتر توربو,1.6 لیتر توربو,1405,0,تهران / میرداماد,اتوماتیک,بنزینی,سفید,مشکی,بدون رنگ,crossover,4 سیلندر,4,2026-10-12T09:48:06.4,lucano,0,https://bama.ir/car/detail-4xe7cfvb-lucano-l7-...,2026-10-14
2,هیوندای، النترا,2025 | 1.5 لیتر,1.5 لیتر,2025,0,تهران / ستارخان,اتوماتیک,بنزینی,سفید,مشکی,بدون رنگ,passenger_car,4 سیلندر,3,2026-09-19T13:12:43.71,hyundai,6700000000,https://bama.ir/car/detail-s4abyrv3-hyundai-el...,2026-10-14
3,چانگان، CS 55 پلاس,2024 | 1.5 لیتر توربو,1.5 لیتر توربو,2024,28000,تهران / ولنجک,اتوماتیک,بنزینی,خاکستری,مشکی,بدون رنگ,crossover,4 سیلندر,6,2026-10-12T19:16:06.27,changan,6550000000,https://bama.ir/car/detail-vybyrlkv-changan-cs...,2026-10-14
4,کی ام سی، T8,1403,دنده ای,1403,30000,تهران / میرداماد,دنده ای,بنزینی,مشکی,مشکی,بدون رنگ,pickup,4 سیلندر,2,2026-10-13T21:13:28.18,kmc,0,https://bama.ir/car/detail-fpvuq3wv-kmc-t8-1403,2026-10-14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39656,ب ام و، سری 5 سدان,2015 | 528i,528i,2015,77000,اصفهان / سعادت آباد,اتوماتیک,بنزینی,سفید,مارون,بدون رنگ,passenger_car,4 سیلندر,8,2025-09-07T11:40:13.65,bmw,0,https://bama.ir/car/detail-nyzsdxyl-bmw-5serie...,2026-10-14
39657,ب ام و، سری 5 سدان,2018 | 530i,530i,2018,49000,اصفهان / خیابان نظر غربی,اتوماتیک,بنزینی,مشکی,موکا,بدون رنگ,passenger_car,4 سیلندر,11,2025-01-15T20:24:22.58,bmw,0,https://bama.ir/car/detail-mcdae3b9-bmw-5serie...,2026-10-14
39658,نیسان، ترا,1404 | اکسکلوسیو,اکسکلوسیو,1404,0,اصفهان / سعادت آباد,اتوماتیک,بنزینی,مشکی,مارون,بدون رنگ,suv,4 سیلندر,7,2025-08-30T11:23:21.82,nissan,0,https://bama.ir/car/detail-wtgptycz-nissan-ter...,2026-10-14
39659,ب ام و، سری 7,2017 | 730li,730li,2017,42000,اصفهان / خیابان نظر غربی,اتوماتیک,بنزینی,سفید صدفی,مارون,بدون رنگ,passenger_car,4 سیلندر,0,2024-01-23T13:42:27.1,bmw,0,https://bama.ir/car/detail-lm8xhqo2-bmw-7serie...,2026-10-14
39660,پراید، صندوق دار,1387,دنده ای,1387,300000,شاهین دژ / پمپ بنزین,دنده ای,بنزینی,نقره ای,طوسی,بدون رنگ,passenger_car,4 سیلندر,1,2020-04-06T09:43:11.21,pride,0,https://bama.ir/car/detail-4y13ydvg-pride-seda...,2026-10-14